version: '3.4'

services:
  k6:
    container_name: "loadtesting_environment"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - loadtesting
#      - spryker_b2b_marketplace_private
#      - spryker_b2b_marketplace_dev_private
#      - spryker_b2c_marketplace_dev_private
#      - spryker_b2b_dev_private
#      - spryker_b2c_dev_private
#      - spryker_b2b_marketplace_private
#      - spryker_b2c_marketplace_private
#      - spryker_b2b_private
#      - spryker_b2c_private
    environment:
        - K6_SCRIPT=${K6_SCRIPT}
        - K6_HOSTENV=${K6_HOSTENV}
        - K6_STATSD_ENABLE_TAGS=true
        - K6_OUT=${K6_OUT}
        - K6_STATSD_ADDR=${K6_STATSD_ADDR}
        - K6_STATSD_NAMESPACE=${K6_STATSD_NAMESPACE}
        - K6_HTTP_DEBUG=${K6_HTTP_DEBUG}
        - K6_NO_THRESHOLDS=${K6_NO_THRESHOLDS:-true}
        - GIT_HASH=${GIT_HASH}
        - GIT_BRANCH=${GIT_BRANCH}
        - GIT_REPO=${GIT_REPO}
        - GIT_TAG=${GIT_TAG}
        - B2B_MP_AUTH_USERNAME=${B2B_MP_AUTH_USERNAME}
        - B2B_MP_AUTH_PASSWORD=${B2B_MP_AUTH_PASSWORD}
        - B2C_MP_AUTH_USERNAME=${B2C_MP_AUTH_USERNAME}
        - B2C_MP_AUTH_PASSWORD=${B2C_MP_AUTH_PASSWORD}
        - B2B_AUTH_USERNAME=${B2B_AUTH_USERNAME}
        - B2B_AUTH_PASSWORD=${B2B_AUTH_PASSWORD}
        - B2C_AUTH_USERNAME=${B2C_AUTH_USERNAME}
        - B2C_AUTH_PASSWORD=${B2C_AUTH_PASSWORD}
        - DATA_EXCHANGE_PAYLOAD_UPDATE_CHUNK_SIZE=${DATA_EXCHANGE_PAYLOAD_UPDATE_CHUNK_SIZE:-100}
        - DATA_EXCHANGE_PAYLOAD_CHUNK_SIZE=${DATA_EXCHANGE_PAYLOAD_CHUNK_SIZE:-500}
        - DATA_EXCHANGE_TARGET_CATALOG_SIZE=${DATA_EXCHANGE_TARGET_CATALOG_SIZE:-10000}
        - DATA_EXCHANGE_THREADS=${DATA_EXCHANGE_THREADS:-1}
        - DATA_EXCHANGE_CONCRETE_MAX_AMOUNT=${DATA_EXCHANGE_CONCRETE_MAX_AMOUNT:-2}
        - DATA_EXCHANGE_DEBUG=${DATA_EXCHANGE_DEBUG:-0}
    volumes:  
      - .:/home/k6
    ports:
      - "6565:6565"
    links:
      - "nrstatsd"
      - "newrelic"

  newrelic-php-daemon:
    image: newrelic/php-daemon
    networks:
      - loadtesting

  nrstatsd:
    container_name: "new_relic_statsd"
    image: newrelic/nri-statsd:latest
    environment: 
      - NR_ACCOUNT_ID=${NR_ACCOUNT_ID}
      # It appears to be a bug in the statsd image. Despite calling the API key, it only works with a New Relic license key.
      - NR_API_KEY=${NRIA_LICENSE_KEY}
      - NR_EU_REGION=${NR_EU_REGION}
      - NR_LOG_METRICS=true
    hostname: "localpocmachine"
    ports:
      - 8125:8125/udp
    networks:
      - loadtesting
    restart: unless-stopped
  
  newrelic:
    container_name: newrelic-infra
    image: newrelic/infrastructure:latest
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host 
    privileged: true
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - NRIA_LICENSE_KEY=${NRIA_LICENSE_KEY}
    restart: unless-stopped

networks:
  loadtesting:
#  spryker_b2b_marketplace_private:
#    external: true
#  spryker_b2b_marketplace_dev_private:
#    external: true
#  spryker_b2c_marketplace_dev_private:
#    external: true
#  spryker_b2c_dev_private:
#    external: true
#  spryker_b2b_dev_private:
#    external: true
#  spryker_b2b_marketplace_private:
#    external: true
#  spryker_b2c_marketplace_private:
#    external: true
#  spryker_b2c_private:
#    external: true
#  spryker_b2b_private:
#    external: true
