services:
  k6:
    container_name: "loadtesting_environment"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - loadtesting
      # - spryker_demo_private
      # - spryker_demo_public
      # - spryker_b2b_marketplace_dev_private
      # - spryker_b2c_marketplace_dev_private
      # - spryker_b2b_dev_private
      # - spryker_b2c_dev_private
      # - spryker_b2b_marketplace_private
      # - spryker_b2c_marketplace_private
      # - spryker_b2b_private
      # - spryker_b2c_private

    environment:
        - K6_SCRIPT=${K6_SCRIPT}
        - K6_HOSTENV=${K6_HOSTENV:-local}
        - K6_INSECURE_SKIP_TLS_VERIFY=true
        - K6_STATSD_ENABLE_TAGS=true
        - K6_OUT=
        - K6_STATSD_ADDR=${K6_STATSD_ADDR:-''}
#        - K6_BROWSER_TIMEOUT:${K6_BROWSER_TIMEOUT:-'60s'}
        - K6_STATSD_NAMESPACE=${K6_STATSD_NAMESPACE}
        - K6_HTTP_DEBUG=${K6_HTTP_DEBUG}
        - K6_NO_THRESHOLDS=${K6_NO_THRESHOLDS:-false}
        - DATA_EXCHANGE_PAYLOAD_PUT_CHUNK_SIZE=${DATA_EXCHANGE_PAYLOAD_PUT_CHUNK_SIZE:-100}
        - DATA_EXCHANGE_PAYLOAD_PATCH_CHUNK_SIZE=${DATA_EXCHANGE_PAYLOAD_PATCH_CHUNK_SIZE:-100}
        - DATA_EXCHANGE_PAYLOAD_CHUNK_SIZE=${DATA_EXCHANGE_PAYLOAD_CHUNK_SIZE:-100}
        - DATA_EXCHANGE_TARGET_CATALOG_SIZE_POST=${DATA_EXCHANGE_TARGET_CATALOG_SIZE_POST:-3000}
        - DATA_EXCHANGE_TARGET_CATALOG_SIZE_PUT_PATCH=${DATA_EXCHANGE_TARGET_CATALOG_SIZE_PUT_PATCH:-1000}
        - DATA_EXCHANGE_THREADS_PATCH=${DATA_EXCHANGE_THREADS_PATCH:-1}
        - DATA_EXCHANGE_THREADS_PUT=${DATA_EXCHANGE_THREADS_PUT:-1}
        - DATA_EXCHANGE_THREADS_POST=${DATA_EXCHANGE_THREADS_POST:-1}
        - DATA_EXCHANGE_STORE_WHITELIST=${DATA_EXCHANGE_STORE_WHITELIST:-}
        - DATA_EXCHANGE_ACTIVATE_PRODUCTS=${DATA_EXCHANGE_ACTIVATE_PRODUCTS:-true}
        - DATA_EXCHANGE_CONCRETE_MAX_AMOUNT=${DATA_EXCHANGE_CONCRETE_MAX_AMOUNT:-1}
        - DATA_EXCHANGE_USE_DEFAULT_STORE_LOCALE=${DATA_EXCHANGE_USE_DEFAULT_STORE_LOCALE:-0}
        - DATA_EXCHANGE_DEBUG=${DATA_EXCHANGE_DEBUG:-0}
        - DATA_EXCHANGE_THREADS_GET=${DATA_EXCHANGE_THREADS_GET:-1}
#        - DATA_EXCHANGE_SINGLE_PRODUCT=${DATA_EXCHANGE_SINGLE_PRODUCT:-0}
        - DATA_EXCHANGE_ENV=${DATA_EXCHANGE_ENV:-DEX}
        - DMS_AMOUNT_OF_STORES=${DMS_AMOUNT_OF_STORES:-40}
        - DMS_AMOUNT_OF_LOCALES=${DMS_AMOUNT_OF_LOCALES:-30}
        - DMS_STORES_CONFIGURATION_FILE=${DMS_STORES_CONFIGURATION_FILE:-'tests/dex/tests/data/stores.json'}
        - SCREENSHOT_ACTIVE=${SCREENSHOT_ACTIVE:-0}
        - USE_EXISTING_CUSTOMER_ACCOUNTS=${USE_EXISTING_CUSTOMER_ACCOUNTS:-0}
        - USE_PREDEFINED_PRODUCTS=${USE_PREDEFINED_PRODUCTS:-0}
        - GIT_HASH=${GIT_HASH:-'-'}
        - GIT_BRANCH=${GIT_BRANCH:-'-'}
        - GIT_REPO=${GIT_REPO:-'-'}
        - GIT_TAG=${GIT_TAG:-'-'}
        - SPRYKER_TEST_RUN_ID=${SPRYKER_TEST_RUN_ID:-'-'}
        - SPRYKER_TEST_RUNNER_HOSTNAME=${SPRYKER_TEST_RUNNER_HOSTNAME:-'-'}
        - BASIC_AUTH_USERNAME=${BASIC_AUTH_USERNAME}
        - BASIC_AUTH_PASSWORD=${BASIC_AUTH_PASSWORD}
        - SPRYKER_TEST_ENVIRONMENT=${SPRYKER_TEST_ENVIRONMENT:-'-'}
        - VALIDATE_VISITED_URL=${VALIDATE_VISITED_URL:-0}
        - MAX_CART_SIZE=${MAX_CART_SIZE:-2}
        - RANDOM_CART_SIZE_WITHIN_TARGET_MAX=${RANDOM_CART_SIZE_WITHIN_TARGET_MAX:-0}
        - STORE=${STORE:-de}
        - STORES_FROM_ENV=${STORES_FROM_ENV:-0}
        - SUMMARY_FILE_FULL_PATH=${SUMMARY_FILE_FULL_PATH:-'summary.json'}
        - AMOUNT_OF_CHECKOUT_ITERATIONS=${AMOUNT_OF_CHECKOUT_ITERATIONS:-10}
        - AMOUNT_OF_CHECKOUT_VUS=${AMOUNT_OF_CHECKOUT_VUS:-10}
        - AMOUNT_OF_BACKOFFICE_ITERATIONS=${AMOUNT_OF_BACKOFFICE_ITERATIONS:-10}
        - AMOUNT_OF_BACKOFFICE_VUS=${AMOUNT_OF_BACKOFFICE_VUS:-10}
        - AMOUNT_OF_RAMP_VUS=${AMOUNT_OF_RAMP_VUS:-30}
        - RAMP_STAGE_DURATION=${RAMP_STAGE_DURATION:-10}
        - K6_BROWSER_HEADLESS=true
#        - K6_BROWSER_ARGS="no-sandbox disable-dev-shm-usage arc-disable-gms-core-cache disable-backgrounding-occluded-windows disable-demo-mode disable-dev-shm-usage disable-web-security disable-zero-browsers-open-for-tests arc-disable-media-store-maintenance arc-disable-tts-cache"
#        - K6_BROWSER_ARGS="no-sandbox disable-web-security"
        - DEX_AUTH_USERNAME=${DEX_AUTH_USERNAME}
        - DEX_AUTH_PASSWORD=${DEX_AUTH_PASSWORD}
        - PTL_AUTH_USERNAME=${PTL_AUTH_USERNAME}
        - PTL_AUTH_PASSWORD=${PTL_AUTH_USERNAME}
        - OTEL_DEMO_AUTH_USERNAME=${PTL_AUTH_USERNAME}
        - OTEL_DEMO_AUTH_PASSWORD=${PTL_AUTH_USERNAME}
        - DMS_AUTH_USERNAME=${DMS_AUTH_USERNAME}
        - DMS_AUTH_PASSWORD=${DMS_AUTH_PASSWORD}
    volumes:
      - .:/home/k6
    ports:
      - "6565:6565"

networks:
  loadtesting:
  spryker-cloud_private:
    external: true
  spryker-cloud_public:
    external: true
  spryker_public:
    external: true
  spryker_private:
    external: true
  spryker_demo_public:
    external: true
  spryker_demo_private:
    external: true
  spryker_b2b_marketplace_private:
    external: true
  spryker_b2b_marketplace_dev_private:
    external: true
  spryker_b2c_marketplace_dev_private:
    external: true
  spryker_b2c_dev_private:
    external: true
  spryker_b2b_dev_private:
    external: true
  spryker_b2c_marketplace_private:
    external: true
  spryker_b2c_private:
    external: true
  spryker_b2b_private:
    external: true
